version: '3'

services:
  api:
    build:
      context: ./Services/api-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      API_HOST : ${API_HOST}
      API_PORT : ${API_PORT}
    ports:
      - 5000:${API_PORT}
    command: python run.py