version: '3'

volumes:
  characters-db:


services:
  api:
    build:
      context: ./Services/api-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      API_HOST : ${API_HOST}
      API_PORT : ${API_PORT}
      DB_NAME : ${DB_NAME}
    ports:
      - 5000:${API_PORT}
    volumes:
      - characters-db:/app/${DB_NAME}
    command: python run.py